// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    partial class ParksApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "",
                            Country = "Namibia",
                            Name = "Etosha National Park",
                            Size = 8600,
                            State = ""
                        },
                        new
                        {
                            ParkId = 2,
                            City = "",
                            Country = "USA",
                            Name = "Grand Canyon National Park",
                            Size = 1904,
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 3,
                            City = "",
                            Country = "India",
                            Name = "Jim Corbett National Park",
                            Size = 201,
                            State = "Uttarakhand"
                        },
                        new
                        {
                            ParkId = 4,
                            City = "",
                            Country = "South Africa",
                            Name = "Kruger National Park",
                            Size = 7512,
                            State = ""
                        },
                        new
                        {
                            ParkId = 5,
                            City = "",
                            Country = "Italy",
                            Name = "Dolomiti Bellunesi National Park",
                            Size = 1,
                            State = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
